import {
  SiReact,
  SiTypescript,
  SiNextdotjs,
  SiNodedotjs,
  SiJavascript,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiGit,
  SiGithub,
  SiFigma,
  SiVite,
  SiNpm,
  SiSass,
  SiExpress,
  SiMongodb,
  SiPostman,
  SiBootstrap,
  SiCssmodules,
  SiVercel,
} from "react-icons/si";

export const techStack = [
  {
    name: "React",
    category: "Frontend",
    color: "#61DAFB",
    icon: <SiReact />,
  },
  {
    name: "Next.js",
    category: "Frontend",
    color: "#ffff",
    icon: <SiNextdotjs />,
  },
  {
    name: "JavaScript",
    category: "Frontend",
    color: "#F7DF1E",
    icon: <SiJavascript />,
  },
  {
    name: "TypeScript",
    category: "Frontend",
    color: "#3178C6",
    icon: <SiTypescript />,
  },
  {
    name: "HTML5",
    category: "Frontend",
    color: "#E34F26",
    icon: <SiHtml5 />,
  },
  {
    name: "CSS3",
    category: "Frontend",
    color: "#1572B6",
    icon: <SiCss />,
  },
  {
    name: "Tailwind CSS",
    category: "UI",
    color: "#06B6D4",
    icon: <SiTailwindcss />,
  },
  {
    name: "Node.js",
    category: "Backend",
    color: "#339933",
    icon: <SiNodedotjs />,
  },
  {
    name: "Git",
    category: "Versionamento",
    color: "#F05032",
    icon: <SiGit />,
  },
  {
    name: "GitHub",
    category: "Versionamento",
    color: "#ffff",
    icon: <SiGithub />,
  },
  {
    name: "Figma",
    category: "Design",
    color: "#F24E1E",
    icon: <SiFigma />,
  },
  {
    name: "Vite",
    category: "Tools",
    color: "#646CFF",
    icon: <SiVite />,
  },
  {
    name: "npm",
    category: "Tools",
    color: "#CB3837",
    icon: <SiNpm />,
  },
  {
    name: "Sass",
    category: "UI",
    color: "#CC6699",
    icon: <SiSass />,
  },
  {
    name: "Express",
    category: "Backend",
    color: "#ffff",
    icon: <SiExpress />,
  },
  {
    name: "MongoDB",
    category: "Backend",
    color: "#47A248",
    icon: <SiMongodb />,
  },
  {
    name: "Postman",
    category: "Backend",
    color: "#E33332",
    icon: <SiPostman />,
  },
  {
    name: "Bootstrap",
    category: "UI",
    color: "#b132e3",
    icon: <SiBootstrap />,
  },
  {
    name: "CSS Modules",
    category: "UI",
    color: "#ffffff",
    icon: <SiCssmodules />,
  },
  {
    name: "Vercel",
    category: "Tools",
    color: "#ffffff",
    icon: <SiVercel />,
  },

];
